### ISSUE TITLE
MacOS pyncnn, import ncnn then Expected in: flat namespace

### ISSUE THREAD

**Issue by zzningxp** [Tencent/ncnn#2654]
pip install from source code, followed readme of pyncnn.

```
~/Develop/ncnn/python(master*) » python3
Python 3.8.2 (default, Oct  2 2020, 10:45:42)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ncnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Develop/ncnn/python/ncnn/__init__.py", line 15, in <module>
    from .ncnn import *
ImportError: dlopen(~/Develop/ncnn/python/ncnn/ncnn.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: ~/Develop/ncnn/python/ncnn/ncnn.so
  Expected in: flat namespace
 in ~/Develop/ncnn/python/ncnn/ncnn.so
>>> 
```

**Comment by zzningxp** [comment]
Found solution:

my cmake target the default version of python to 2.7
use this to avoid:
`cmake -DNCNN_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 ..`
