### ISSUE TITLE
ncnnoptimize Segmentation fault

### ISSUE THREAD

**Issue by chingi071** [Tencent/ncnn#2673]
您好，我照著您的步驟將 yolact 模型做轉換: https://zhuanlan.zhihu.com/p/128974102
在 0x3 去掉后处理导出onnx 這個步驟時，出現了以下錯誤，請問該怎麼解決呢? 謝謝您。
```
Multiple GPUs detected! Turning off JIT.
Config not specified. Parsed yolact_resnet50_config from the file name.

Loading model... Done.
/home/joy/yolact/yolact.py:222: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.last_img_size != (cfg._tmp_img_w, cfg._tmp_img_h):
Traceback (most recent call last):
  File "eval.py", line 1107, in <module>
    evaluate(net, dataset)
  File "eval.py", line 883, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 601, in evalimage
    torch.onnx._export(net, batch, "yolact.onnx", export_params=True, keep_initializers_as_inputs=True, opset_version=11)
  File "/home/aderd/anaconda3/envs/pytorch_v37/lib/python3.7/site-packages/torch/onnx/__init__.py", line 28, in _export
    result = utils._export(*args, **kwargs)
  File "/home/aderd/anaconda3/envs/pytorch_v37/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/aderd/anaconda3/envs/pytorch_v37/lib/python3.7/site-packages/torch/onnx/utils.py", line 409, in _model_to_graph
    _export_onnx_opset_version)
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu
```

**Comment by chingi071** [comment]
我将torch版本改为 1.5.0, torchvision 0.6.0 可以成功转换onnx (原版本 torch 1.6.0, torchvision 0.7.0)
在 0x5 ncnn模型转换和优化的部分，执行 onnx2ncnn 可以成功输出yolact.param, yolact.bin，
但执行 ./ncnnoptimize yolact.param yolact.bin yolact-opt.param yolact-opt.bin 0 指令会出现Segmentation fault (core dumped) 的错误讯息，请问该怎么解决呢? 谢谢您。

**Comment by chingi071** [comment]
您好，想请问一下,以下是转换为onnx时的错误讯息,会是因为这个原因导致ncnnoptimize出错吗? 以下的指令是可以成功输出onnx。再麻烦您了，谢谢。
```
$ python eval.py --trained_model=weights/yolact_resnet50_54_800000.pth --score_threshold=0.15 --top_k=15 --image=test.jpg
Multiple GPUs detected! Turning off JIT.
Config not specified. Parsed yolact_resnet50_config from the file name.

Loading model... Done.
/home/aderd/joy/yolact_v2/yolact.py:221: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.last_img_size != (cfg._tmp_img_w, cfg._tmp_img_h):

```

**Comment by john-lihn** [comment]
@chingi071 我剛看過您傳的教學 並嘗試執行過, 我也發現出現問題 不過我在查看他那段節點的輸出結果發現 應該是他輸出格式沒有一樣才產生的錯誤
```
Multiple GPUs detected! Turning off JIT.
Config not specified. Parsed yolact_resnet50_config from the file name.

Loading model... Done.
None
None
None
None
None
(550, 550)
C:\Users\USER\Desktop\yolact-master\yolact.py:222: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.last_img_size != (cfg._tmp_img_w, cfg._tmp_img_h):
(550, 550)
(550, 550)
(550, 550)
(550, 550)
```

**Comment by john-lihn** [comment]
你要使用看看官方pytorch版本1.0.1嗎

**Comment by nihui** [comment]
请尝试更新下 onnx2ncnn 和 ncnnoptimize 代码，最近修了几个 bug ....

**Comment by john-lihn** [comment]
@nihui 謝謝 我會在試試看的 辛苦了

**Comment by chingi071** [comment]
@nihui 非常感謝您! 我再試試看。

**Comment by chingi071** [comment]
@nihui 您好，非常感谢您的帮助。但我在执行 ncnnoptimize 一样会出现Segmentation fault 的错误讯息，操作步骤都是一样的。
我的环境为 torch 1.5.0, torchvision 0.7.0, python 3.7, onnx 1.8.1
想请问是因为环境的关系吗，再麻烦您了，非常感谢。

**Comment by FeiMiBa** [comment]
@nihui 类似的问题
pytorch -> onnx -> 最新版onnx sim -> 最新版onnx2ncnn成功 -> 该版本下ncnnoptimize失败: segmentation fault (core dumped)
pytorch -> onnx -> 最新版onnx sim -> 2019年某版本onnx2ncnn成功 -> 该版本下ncnnoptimize成功

**Comment by huyunlei** [comment]
@FeiMiBa 非常感谢您,您简直太好的,ncnn版本确实有影响.

**Comment by huyunlei** [comment]
@FeiMiBa  大哥你真是好人啊,ncnn版本确实有影响,十分感谢.看见fault真的很绝望,也不会改,我今天能看到你这回答真的幸运极了,十分感谢,

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
