### ISSUE TITLE
ModuleNotFoundError: No module named 'ncnn.ncnn'

### ISSUE THREAD

**Issue by koumaron** [Tencent/ncnn#2846]
windows 10
visual studio 2017
python 3.7.6
cmake 3.18.4

I tried python wrapper of ncnn with pybind11.
And, I got success message untill installing ncnn.
But, I run benchmark.py, then I got the error message bellow.
I put my all output on command prompt.
Could you give me any advice?

thank you.

`
C:\Users\***\ncnn>git submodule init && git submodule update

C:\Users\***\ncnn>mkdir build

C:\Users\***\ncnn>cd build

C:\Users\***\ncnn\build>cmake -DNCNN_PYTHON=ON ..
-- Building for: Visual Studio 16 2019
-- CMAKE_INSTALL_PREFIX = C:/Users/***/ncnn/build/install
-- NCNN_VERSION_STRING = 1.0.20210414
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target arch: x86
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- OpenCV library: C:/lib/opencv/build
-- version: 4.5.2
-- libraries: opencv_world
-- include path: C:/lib/opencv/build/include
-- Found Protobuf: C:/Users/***/Desktop/protobuf/protobuf-3.4.0/build/install/lib/libprotobuf.lib (found version "3.4.0")
-- pybind11 v2.6.2 dev1
-- Found PythonInterp: C:/Users/***/anaconda3/python.exe (found version "3.7.6")
-- Found PythonLibs: C:/Users/***/anaconda3/libs/python37.lib
-- Performing Test HAS_MSVC_GL_LTCG
-- Performing Test HAS_MSVC_GL_LTCG - Success
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/***/ncnn/build

C:\Users\***\ncnn\build>cd ..

C:\Users\***\ncnn>cd python

C:\Users\***\ncnn\python>pip install .
Processing c:\users\***\ncnn\python
Requirement already satisfied: numpy in c:\users\***\anaconda3\lib\site-packages (from ncnn==1.0.20210414) (1.18.1)
Requirement already satisfied: tqdm in c:\users\***\anaconda3\lib\site-packages (from ncnn==1.0.20210414) (4.31.1)
Requirement already satisfied: requests in c:\users\***\anaconda3\lib\site-packages (from ncnn==1.0.20210414) (2.22.0)
Requirement already satisfied: portalocker in c:\users\***\anaconda3\lib\site-packages\portalocker-2.3.0-py3.7.egg (from ncnn==1.0.20210414) (2.3.0)
Requirement already satisfied: opencv-python in c:\users\***\anaconda3\lib\site-packages (from ncnn==1.0.20210414) (4.2.0.34)
Requirement already satisfied: pywin32!=226 in c:\users\****\anaconda3\lib\site-packages (from portalocker->ncnn==1.0.20210414) (227)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\***\anaconda3\lib\site-packages (from requests->ncnn==1.0.20210414) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\\anaconda3\lib\site-packages (from requests->ncnn==1.0.20210414) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\***\anaconda3\lib\site-packages (from requests->ncnn==1.0.20210414) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\***\anaconda3\lib\site-packages (from requests->ncnn==1.0.20210414) (2.8)
Building wheels for collected packages: ncnn
Building wheel for ncnn (setup.py) ... done
Created wheel for ncnn: filename=ncnn-1.0.20210414-cp37-cp37m-win_amd64.whl size=51630 sha256=81f9a460b9b07e9f585cbf78b56be23c8a66e6e714906ef5dc627def4b4aa855
Stored in directory: C:\Users\***\AppData\Local\Temp\pip-ephem-wheel-cache-uqkehvlz\wheels\6c\e5\e4\e219098e41d334800ade1537bb7e34df1938c3e1c390e8387e
Successfully built ncnn
Installing collected packages: ncnn
Attempting uninstall: ncnn
Found existing installation: ncnn 1.0.20210414
Uninstalling ncnn-1.0.20210414:
Successfully uninstalled ncnn-1.0.20210414
Successfully installed ncnn-1.0.20210414

C:\Users\***\ncnn\python>python tests\benchmark.py
Traceback (most recent call last):
File "tests\benchmark.py", line 17, in
import ncnn
File "C:\Users\***\anaconda3\lib\site-packages\ncnn__init__.py", line 15, in
from .ncnn import *
ModuleNotFoundError: No module named 'ncnn.ncnn'
`

**Comment by Chidhambararajan** [comment]
I guess you forgot the `make` part

**Comment by nihui** [comment]
you can install ncnn python module via `pip install -U ncnn`

**Comment by nihui** [comment]
If the problem persists, feel free to reopen the issue
