### ISSUE TITLE
onnx2ncnn SIGABRT on process dimensionless layer

### ISSUE THREAD

**Issue by bytesuji** [Tencent/ncnn#3042]
## error log | 日志或报错信息 | ログ
After compiling with debug flags, I got
```
./onnx2ncnn /tmp/PostNetSim.onnx
[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:1167] CHECK failed: (index) < (current_size_):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_):
fish: Job 3, “./onnx2ncnn /tmp/PostNetSim.onnx” terminated by signal SIGABRT (Abort)
```

## context | 编译/运行环境 | バックグラウンド
Trying to execute onnx2ncnn on [this model](https://t.me/ncnnyes/2543) from ncnn community. I was trying to debug this issue but was unable to determine a fix.

## how to reproduce | 复现步骤 | 再現方法
1. Download the model
2. Run onnx2ncnn on it
3. Crash T_T

## more | 其他 | その他
Here is a backtrace for this exception:
```
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff78bb859 in __GI_abort () at abort.c:79
#2  0x00007ffff7b64951 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7b7047c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7b704e7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7b70799 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7d66f7c in ?? () from /lib/x86_64-linux-gnu/libprotobuf.so.17
#7  0x00005555555b791e in google::protobuf::RepeatedField<long>::Get (this=0x5555557001c8, index=0)
    at /usr/include/google/protobuf/repeated_field.h:1167
#8  0x00005555555b6d6e in onnx::TensorProto::dims (this=0x5555557001b0, index=0)
    at /home/albert/Documents/ncnn/tools/onnx/onnx.pb.h:5243
#9  0x00005555555ab962 in main (argc=2, argv=0x7fffffffe1f8)
    at /home/albert/Documents/ncnn/tools/onnx/onnx2ncnn.cpp:4023
```
This is occurring because a weight `W` of type `onnx::TensorProto` has `W.dims_size() == 0`, although the procedure assumes it will be greater than this. The model does appear valid when opened with onnx in Python.

**Comment by nihui** [comment]
currently ncnn does not support convolution with runtime generated weight blob

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
