### ISSUE TITLE
coredump happend in ncnn::destroy_gpu_instance()

### ISSUE THREAD

**Issue by arnoldfychen** [Tencent/ncnn#3260]
## error log | 日志或报错信息 | ログ
scrfd: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
Aborted (core dumped)

I got the backtrace by gdb:

Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f93a089f240 (LWP 12011))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f939e56f921 in __GI_abort () at abort.c:79
#2  0x00007f939e55f48a in __assert_fail_base (fmt=0x7f939e6e6750 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x7f93a02b5d40 "new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)", file=file@entry=0x7f93a02b5d34 "tpp.c", line=line@entry=84,
    function=function@entry=0x7f93a02b5df0 <__PRETTY_FUNCTION__.7568> "__pthread_tpp_change_priority") at assert.c:92
#3  0x00007f939e55f502 in __GI___assert_fail (assertion=assertion@entry=0x7f93a02b5d40 "new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)",
    file=file@entry=0x7f93a02b5d34 "tpp.c", line=line@entry=84, function=function@entry=0x7f93a02b5df0 <__PRETTY_FUNCTION__.7568> "__pthread_tpp_change_priority") at assert.c:101
#4  0x00007f93a02b464f in __pthread_tpp_change_priority (previous_prio=previous_prio@entry=-1, new_prio=new_prio@entry=0) at tpp.c:82
#5  0x00007f93a02aabed in __pthread_mutex_lock_full (mutex=0x55ae7cf8f5f8) at ../nptl/pthread_mutex_lock.c:552
#6  0x00007f9381d98ca5 in ?? () from /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0
#7  0x00007f9384de06fb in eglReleaseThread () from /usr/lib/x86_64-linux-gnu/libEGL.so.1
#8  0x00007f9388148557 in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#9  0x00007f9388147309 in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#10 0x00007f93a0704e40 in _dl_close_worker (map=map@entry=0x55ae7a6a4c50, force=force@entry=false) at dl-close.c:293
#11 0x00007f93a0705c4a in _dl_close_worker (force=false, map=0x55ae7a6a4c50) at dl-close.c:125
#12 _dl_close (_map=0x55ae7a6a4c50) at dl-close.c:842
#13 0x00007f939e6961ef in __GI__dl_catch_exception (exception=exception@entry=0x7fff2b0d3f60, operate=operate@entry=0x7f939e32c070 <dlclose_doit>, args=args@entry=0x55ae7a6a4c50)
    at dl-error-skeleton.c:196
#14 0x00007f939e69627f in __GI__dl_catch_error (objname=objname@entry=0x55ae7a6a5c80, errstring=errstring@entry=0x55ae7a6a5c88, mallocedp=mallocedp@entry=0x55ae7a6a5c78,
    operate=operate@entry=0x7f939e32c070 <dlclose_doit>, args=args@entry=0x55ae7a6a4c50) at dl-error-skeleton.c:215
#15 0x00007f939e32c745 in _dlerror_run (operate=operate@entry=0x7f939e32c070 <dlclose_doit>, args=0x55ae7a6a4c50) at dlerror.c:162
#16 0x00007f939e32c0b3 in __dlclose (handle=<optimized out>) at dlclose.c:46
#17 0x00007f93a0067acf in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan.so.1
#18 0x00007f93a0071248 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan.so.1
#19 0x000055ae77df2c7d in ncnn::destroy_gpu_instance() ()
#20 0x00007f939e572161 in __run_exit_handlers (status=0, listp=0x7f939e91a718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#21 0x00007f939e57225a in __GI_exit (status=<optimized out>) at exit.c:139
#22 0x00007f939e550bfe in __libc_start_main (main=0x55ae77db4c80 <main>, argc=2, argv=0x7fff2b0d4188, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fff2b0d4178) at ../csu/libc-start.c:344
#23 0x000055ae77db5eba in _start ()

## context | 编译/运行环境 | バックグラウンド
X86-64 server, RTX3090 GPU, Ubuntu18.04, vulkan 1.2.189, the latest ncnn 
## how to reproduce | 复现步骤 | 再現方法
1. instll vulkan sdk 1.2.189
2. export VULKAN_SDK=/data/workspace/vulkan-1.2.189/x86_64
3. git clone git@github.com:Tencent/ncnn
4. cd ncnn
5. git submodule update --init
6. mkdir build && cd build
7. cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=ON -DNCNN_BUILD_EXAMPLES=ON ..
8. make -j$(nproc)
9. cd examples
10. copy scrfd_500m-opt2.bin and scrfd_500m-opt2.param to this folder and cp a test image test.jpg to this folder
11. ./scrfd test.jpg
12. You will see coredump happens almost when program ends.

**Comment by shenck0** [comment]
same problem,
env: X86-64 server, RTX2080 GPU, Ubuntu18.04, vulkan 1.2.141, ncnn 1.0.20220527

**Comment by nihui** [comment]
please update to the latest ncnn library, which has workaround for this issue
If the problem persists, feel free to reopen the issue
