### ISSUE TITLE
with io.open("CMakeLists.txt", encoding="utf8") as f:   FileNotFoundError: [Errno 2] No such file or directory: 'CMakeLists.txt'

### ISSUE THREAD

**Issue by hbhhwxk** [Tencent/ncnn#3406]
## error log | 日志或报错信息 | ログ
Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/mr/vc0p_j4j55sdq_m7hl6qs3q00000gn/T/tmpoc2b_mpp
       cwd: /private/var/folders/mr/vc0p_j4j55sdq_m7hl6qs3q00000gn/T/pip-install-lv301uxf/ncnn
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/mr/vc0p_j4j55sdq_m7hl6qs3q00000gn/T/pip-build-env-krits8wx/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/private/var/folders/mr/vc0p_j4j55sdq_m7hl6qs3q00000gn/T/pip-build-env-krits8wx/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/mr/vc0p_j4j55sdq_m7hl6qs3q00000gn/T/pip-build-env-krits8wx/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 134, in <module>
      version=find_version(),
    File "setup.py", line 13, in find_version
      with io.open("CMakeLists.txt", encoding="utf8") as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'CMakeLists.txt'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/mr/vc0p_j4j55sdq_m7hl6qs3q00000gn/T/tmpoc2b_mpp Check the logs for full command output.
## context | 编译/运行环境 | バックグラウンド
mac osx
## how to reproduce | 复现步骤 | 再現方法
1.pip3 install -U ncnn

**Comment by nihui** [comment]
```
cd ncnn
pip install .
```
