### ISSUE TITLE
macos 安装python ncnn失败

### ISSUE THREAD

**Issue by ChaoII** [Tencent/ncnn#3962]
##### 环境：
- 系统：macos 12.2 intel i5 x86
- python版本：python3.8.5
##### 问题：
- 执行`pip install ncnn`报找不到Cmakelists.txt的错误
- 在源码（`cd ncnn`）执行 `python steup.py install `成功安装`ncnn`但是执行`import ncnn`报错没有ncnn.ncnn 模块错误，导致无法进行快速验证。
请问这一块该怎么处理？

**Comment by zchrissirhcz** [comment]
I can confirm this on my mac (m1) with miniforge installed python3.9.10

```
(base) ➜  model_zoo git:(examples-early-stop-if-load-models-failed) ✗ pip install -U ncnn
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting ncnn
  Downloading http://mirrors.aliyun.com/pypi/packages/20/98/8e46767ec120bd61d5bdbe85f26a451dbb5a4978541ad1881e38bde822aa/ncnn-1.0.20220701.tar.gz (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/zz/soft/miniforge3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/zz/soft/miniforge3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/zz/soft/miniforge3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/kz/zl8nc1654c58czlnmx7ssrk80000gn/T/pip-build-env-3n86n_uy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/kz/zl8nc1654c58czlnmx7ssrk80000gn/T/pip-build-env-3n86n_uy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/kz/zl8nc1654c58czlnmx7ssrk80000gn/T/pip-build-env-3n86n_uy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 128, in <module>
          version=find_version(),
        File "setup.py", line 13, in find_version
          with io.open("CMakeLists.txt", encoding="utf8") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'CMakeLists.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(base) ➜  model_zoo git:(examples-early-stop-if-load-models-failed) ✗ pip install -U ncnn
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting ncnn
  Using cached http://mirrors.aliyun.com/pypi/packages/20/98/8e46767ec120bd61d5bdbe85f26a451dbb5a4978541ad1881e38bde822aa/ncnn-1.0.20220701.tar.gz (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/zz/soft/miniforge3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/zz/soft/miniforge3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/zz/soft/miniforge3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/kz/zl8nc1654c58czlnmx7ssrk80000gn/T/pip-build-env-bl6x6cka/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/kz/zl8nc1654c58czlnmx7ssrk80000gn/T/pip-build-env-bl6x6cka/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/kz/zl8nc1654c58czlnmx7ssrk80000gn/T/pip-build-env-bl6x6cka/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 128, in <module>
          version=find_version(),
        File "setup.py", line 13, in find_version
          with io.open("CMakeLists.txt", encoding="utf8") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'CMakeLists.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by zchrissirhcz** [comment]
> ##### 环境：
> * 系统：macos 12.2 intel i5 x86
> * python版本：python3.8.5
> 
> ##### 问题：
> * 执行`pip install ncnn`报找不到Cmakelists.txt的错误
> * 在源码（`cd ncnn`）执行 `python steup.py install `成功安装`ncnn`但是执行`import ncnn`报错没有ncnn.ncnn 模块错误，导致无法进行快速验证。
>   请问这一块该怎么处理？

我的 python 环境是 miniforge 安装的（和 miniconda 基本一样），我是用 `pip install .` 命令安装的。安装后， `import ncnn` 不会报错，可考虑尝试。

**Comment by ChaoII** [comment]
@zchrissirhcz ZZ佬，你好，按照你的方法`pip install .` 确实成功安装了，感谢！

**Comment by redthing1** [comment]
Same issue.
