### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by hhxdestiny** [Tencent/ncnn#4605]
目标机器是centos7，非常奇葩的一个错误，请大佬看看：
1. 在windows及ubuntu20.04以动态库方式调用均正常，然后在centos7上出现段错误的情况，解决未遂。
2. 容器化部署，docker镜像使用ubuntu22.04，同一个code在ubuntu系统的ubuntu22.04容器中正常运行，在centos系统上部署同样的ubuntu22.04容器报下面的错误，以为是centos7默认docker版本过低，更新docker至最新后，错误依旧。
```bash
Floating point exception (core dumped)
```
在devel容器中gdb，得到以下信息：
```bash
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffebb2f640 (LWP 295)]
[New Thread 0x7fffeb32e640 (LWP 296)]

Thread 1 "image_classifie" received signal SIGFPE, Arithmetic exception.
0x0000555555e21802 in ncnn::get_optimal_tile_mnk(int, int, int, int, int, int, int&, int&, int&, int) ()
```
* centos7镜像来源: https://mirrors.aliyun.com/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2207-02.iso
* Dockerfile:
```Dockerfile
FROM ubuntu:22.04

ENV TIME_ZONE=Asiz/Shanghai

RUN set -x && \
    apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get install tzdata && \
    echo "${TIME_ZONE}" > /etc/timezone && \
    ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime && \
    apt-get install -y \
    build-essential \
    cmake \
    pkg-config \
    gcc \
    g++ \
    wget \
    tar \
    zip \
    unzip \
    vim \
    git \
    libvulkan-dev \
    libopencv-dev \
    libprotobuf-dev \
    protobuf-compiler

WORKDIR /home/root/app
```

**Comment by hhxdestiny** [comment]
补充一下调用堆栈
```bash
(gdb) bt
#0  0x0000555555e21802 in ncnn::get_optimal_tile_mnk(int, int, int, int, int, int, int&, int&, int&, int) ()
#1  0x0000555555e21bfe in ncnn::Gemm_x86::create_pipeline(ncnn::Option const&) ()
#2  0x000055555584ffd5 in ncnn::Convolution_x86::create_pipeline(ncnn::Option const&) ()
#3  0x0000555555784d88 in ncnn::Net::load_model(ncnn::DataReader const&) ()
#4  0x00005555557854e5 in ncnn::Net::load_model(char const*) ()
#5  0x0000555555702fa0 in ai::vision::yolov5::yolov5 (this=0x55555693d080, model_path="model", conf=0.300000012, iou=0.449999988, img_size=640)
```

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4610

**Comment by nihui** [comment]
fell free to reopen issue if it still resists
