### ISSUE TITLE
yolov8s-pose转ncnn

### ISSUE THREAD

**Issue by Rachel-liuqr** [Tencent/ncnn#4649]
## model | 模型 | モデル
1. original model：yolov8s-pose.pt

## how to reproduce | 复现步骤 | 再現方法
1.yolov8s-pose.pt转onnx后，再使用ncnn2onnx时报错：
Unsupported slice step!
ScatterND not supported yet！

2.然后尝试先转为torchscript
转torchscript代码如下：
from ultralytics import YOLO
model = YOLO("yolov8s-pose.pt")  # load a pretrained model (recommended for training)
success = model.export(format="torchscript", simplify=True)  # export the model to onnx format
assert success

再使用pnnx工具转模型，输入命令如下
./pnnx  yolov8s-pose.torchscript  inputshape=[1,3,640,640]
报错如下
pnnxparam = yolov8s-pose.pnnx.param
pnnxbin = yolov8s-pose.pnnx.bin
pnnxpy = yolov8s-pose_pnnx.py
pnnxonnx = yolov8s-pose.pnnx.onnx
ncnnparam = yolov8s-pose.ncnn.param
ncnnbin = yolov8s-pose.ncnn.bin
ncnnpy = yolov8s-pose_ncnn.py
fp16 = 1
optlevel = 2
device = cpu
inputshape = [1,3,640,640]f32
inputshape2 = 
customop = 
moduleop = 
############# pass_level0
inline module = ultralytics.nn.modules.Bottleneck
inline module = ultralytics.nn.modules.C2f
inline module = ultralytics.nn.modules.Concat
inline module = ultralytics.nn.modules.Conv
inline module = ultralytics.nn.modules.DFL
inline module = ultralytics.nn.modules.Pose
inline module = ultralytics.nn.modules.SPPF
inline module = ultralytics.nn.modules.Bottleneck
inline module = ultralytics.nn.modules.C2f
inline module = ultralytics.nn.modules.Concat
inline module = ultralytics.nn.modules.Conv
inline module = ultralytics.nn.modules.DFL
inline module = ultralytics.nn.modules.Pose
inline module = ultralytics.nn.modules.SPPF

----------------

############# pass_level1
unknown Parameter value kind prim::Constant of TensorType, t.dim = 2
unknown Parameter value kind prim::Constant of TensorType, t.dim = 2
unknown Parameter value kind prim::Constant of TensorType, t.dim = 2
unknown Parameter value kind prim::Constant of TensorType, t.dim = 2
unknown Parameter value kind prim::Constant of TensorType, t.dim = 2
unknown Parameter value kind prim::Constant of TensorType, t.dim = 2
############# pass_level5
make_slice_expression input 206
make_slice_expression self 207
make_slice_expression src 209
make_slice_expression input 210
make_slice_expression self 214
make_slice_expression src 216
make_slice_expression input 217
make_slice_expression self 221
make_slice_expression src 223
############# pass_ncnn
force batch axis 233 for operand 212
force batch axis 233 for operand 219
force batch axis 233 for operand pnnx_expr_35_sub(212,5.000000e-01)
force batch axis 233 for operand pnnx_expr_9_sub(219,5.000000e-01)
binaryop broadcast across batch axis 0 and 233 is not supported
binaryop broadcast across batch axis 0 and 233 is not supported
binaryop broadcast across batch axis 0 and 233 is not supported
binaryop broadcast across batch axis 0 and 233 is not supported
binaryop broadcast across batch axis 0 and 233 is not supported
select along batch axis 0 is not supported
select along batch axis 0 is not supported
slice with step 3 is not supported
slice with step 3 is not supported
slice with step 3 is not supported
slice_copy with step 3 is not supported
slice_copy with step 3 is not supported
slice_copy with step 3 is not supported
ignore Crop select_0 param dim=0
ignore Crop select_0 param index=0
ignore Crop select_1 param dim=0
ignore Crop select_1 param index=1

技穷了，请大神赐教！！！

**Comment by triple-Mu** [comment]
https://zhuanlan.zhihu.com/p/622596922
可以参考这个知乎。

**Comment by Rachel-liuqr** [comment]
> https://zhuanlan.zhihu.com/p/622596922 可以参考这个知乎。

谢谢三木，问题解决了！！！

>

**Comment by Rachel-liuqr** [comment]
问题已解决。
[YOLOv8-pose在ncnn框架下部署过程记录（包含ncnn、pnnx安装以及模型结构更改及转换）](https://blog.csdn.net/Rachel321/article/details/130381788)
https://github.com/Rachel-liuqr/yolov8s-pose-ncnn
如果有帮助的话，麻烦star，谢谢！

**Comment by glenn-jocher** [comment]
@Rachel-liuqr I have great news 😃! I've recently added official support for Ultralytics YOLOv8 NCNN export ✅ in PR https://github.com/ultralytics/ultralytics/pull/3529 with the help of @nihui which is part of `ultralytics==8.0.129`. NCNN works for all tasks including Detect, Segment, Pose and Classify.


You can now export with CLI:
```
yolo export model=yolov8n.pt format=ncnn
```

or Python:
```python
from ultralytics import YOLO

# Create a model
model = YOLO('yolov8n.pt')

# Export the model to NCNN with arguments
model.export(format='ncnn', half=True, imgsz=640)
```

Output is a `yolov8n_ncnn_model/` directory containing `model.bin`, `model.param` and `metadata.yaml`, along with extra PNNX files. For details see https://github.com/pnnx/pnnx README.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Please let us know if NCNN export is working correctly for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by goldwater668** [comment]
@glenn-jocher 
Although ncnn has been converted, there is a lack of examples of using c++ to call ncnn. Can this be provided, such as how to display the results predicted by ncnn?

**Comment by goldwater668** [comment]
@triple-Mu 
The following is the inference time of ncnn-gpu, ncnn-cpu and pt-ncnn that I tested. Is this normal? This is tested by yolo prediction code.
https://github.com/ultralytics/ultralytics/issues/3917

**Comment by FaterYU** [comment]
> 问题已解决。 [YOLOv8-pose在ncnn框架下部署过程记录（包含ncnn、pnnx安装以及模型结构更改及转换）](https://blog.csdn.net/Rachel321/article/details/130381788) https://github.com/Rachel-liuqr/yolov8s-pose-ncnn 如果有帮助的话，麻烦star，谢谢！

想问下我按最后的方案执行后会出现以下错误：
```
& ~/python.exe ~/export2ncnn.py
Ultralytics YOLOv8.1.24 🚀 Python-3.9.7 torch-1.9.0+cu111 CPU (11th Gen Intel Core(TM) i7-1165G7 2.80GHz)
D:\software\Anaconda\envs\pytorch\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
YOLOv8n-seg summary (fused): 195 layers, 3404320 parameters, 0 gradients, 12.6 GFLOPs
torch.Size([1, 80, 80, 80]) torch.Size([1, 80, 80, 64]) torch.Size([1, 80, 80, 32])
Traceback (most recent call last):
  File "~\export2ncnn.py", line 10, in <module>
    model.export(format='onnx', opset=11, simplify=True, dynamic=False, imgsz=640)
  File "~\yolov8\ultralytics\engine\model.py", line 587, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "D:\software\Anaconda\envs\pytorch\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "~\yolov8\ultralytics\engine\exporter.py", line 238, in __call__
    y = model(im)  # dry runs
  File "D:\software\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "~\yolov8\ultralytics\nn\tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
  File "~\yolov8\ultralytics\nn\tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "~\yolov8\ultralytics\nn\tasks.py", line 128, in _predict_once
    x = m(x)  # run
  File "D:\software\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "~\yolov8\ultralytics\nn\modules\head.py", line 131, in forward
    results = self.forward_seg_export(x)
  File "~\yolov8\ultralytics\nn\modules\head.py", line 152, in forward_seg_export
    results.append(torch.cat((cls, dfl, mcoef), 1))
RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 80 and 64 in dimension 3 (The offending index is 1)
```

应该如何解决，其中 `torch.Size([1, 80, 80, 80]) torch.Size([1, 80, 80, 64]) torch.Size([1, 80, 80, 32])` 是我 `print(cls.shape, dfl.shape, mcoef.shape)` 出来的三个shape

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by nihui** [comment]
yolov8 example https://github.com/Tencent/ncnn/pull/5506

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
