### ISSUE TITLE
pnnx segment fault

### ISSUE THREAD

**Issue by iamfaith** [Tencent/ncnn#5563]
############# pass_level2

Program received signal SIGSEGV, Segmentation fault.
pnnx::pnnx_graph_rewrite (graph=..., pass=0x555559052c60, opindex=@0x7fffffffd614: 0) at /home/faith/ncnn/tools/pnnx/src/pass_level2.cpp:984
984                 cur = graph.ops[cur_index];
(gdb) where
#0  pnnx::pnnx_graph_rewrite (graph=..., pass=0x555559052c60, opindex=@0x7fffffffd614: 0) at /home/faith/ncnn/tools/pnnx/src/pass_level2.cpp:984
#1  0x00005555555ffaba in pnnx::pass_level2 (g=...) at /home/faith/ncnn/tools/pnnx/src/pass_level2.cpp:1415
#2  0x00005555555ca184 in main (argc=2, argv=0x7fffffffd9a8) at /home/faith/ncnn/tools/pnnx/src/main.cpp:335
(gdb) bt
#0  pnnx::pnnx_graph_rewrite (graph=..., pass=0x555559052c60, opindex=@0x7fffffffd614: 0) at /home/faith/ncnn/tools/pnnx/src/pass_level2.cpp:984
#1  0x00005555555ffaba in pnnx::pass_level2 (g=...) at /home/faith/ncnn/tools/pnnx/src/pass_level2.cpp:1415
#2  0x00005555555ca184 in main (argc=2, argv=0x7fffffffd9a8) at /home/faith/ncnn/tools/pnnx/src/main.cpp:335

## model | 模型 | モデル
1. original model

yolov5 6.2 onnx

## how to reproduce | 复现步骤 | 再現方法
pnnx yolov5n.onnx

**Comment by wzyforgit** [comment]
You need input torchscript instead of onnx
