### ISSUE TITLE
python setup failing 

### ISSUE THREAD

**Issue by xalteropsx** [Tencent/ncnn#5782]
```pt
R:\allc\eaew\ncnn\setup.py:47: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  install.initialize_options(self)
running build
running build_py
creating build\lib.win-amd64-cpython-311
creating build\lib.win-amd64-cpython-311\ncnn
copying python\ncnn\__init__.py -> build\lib.win-amd64-cpython-311\ncnn
creating build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\fasterrcnn.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\mobilenetssd.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\mobilenetv2ssdlite.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\mobilenetv3ssdlite.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\model_store.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\model_zoo.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\nanodet.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\peleenetssd.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\retinaface.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\rfcn.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\shufflenetv2.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\simplepose.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\squeezenet.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\squeezenetssd.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\yolact.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\yolov2.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\yolov3.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\yolov4.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\yolov5.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\yolov7.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\yolov8.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
copying python\ncnn\model_zoo\__init__.py -> build\lib.win-amd64-cpython-311\ncnn\model_zoo
creating build\lib.win-amd64-cpython-311\ncnn\utils
copying python\ncnn\utils\download.py -> build\lib.win-amd64-cpython-311\ncnn\utils
copying python\ncnn\utils\functional.py -> build\lib.win-amd64-cpython-311\ncnn\utils
copying python\ncnn\utils\objects.py -> build\lib.win-amd64-cpython-311\ncnn\utils
copying python\ncnn\utils\visual.py -> build\lib.win-amd64-cpython-311\ncnn\utils
copying python\ncnn\utils\__init__.py -> build\lib.win-amd64-cpython-311\ncnn\utils
running build_ext
-- Building for: Ninja
-- CMAKE_INSTALL_PREFIX = R:/allc/eaew/ncnn/build/temp.win-amd64-cpython-311/Release/install
-- NCNN_VERSION_STRING = 1.0.20241119
CMake Deprecation Warning at CMakeLists.txt:24 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at CMakeLists.txt:45 (project):
  Generator

    Ninja

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "R:\allc\eaew\ncnn\setup.py", line 183, in <module>
    setup(
  File "Z:\software\python11\Lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "Z:\software\python11\Lib\site-packages\setuptools\dist.py", line 976, in run_command
    super().run_command(command)
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "R:\allc\eaew\ncnn\setup.py", line 54, in run
    install.run(self)
  File "Z:\software\python11\Lib\site-packages\setuptools\command\install.py", line 85, in run
    super().run()
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\command\install.py", line 697, in run
    self.run_command('build')
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "Z:\software\python11\Lib\site-packages\setuptools\dist.py", line 976, in run_command
    super().run_command(command)
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "Z:\software\python11\Lib\site-packages\setuptools\dist.py", line 976, in run_command
    super().run_command(command)
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "Z:\software\python11\Lib\site-packages\setuptools\command\build_ext.py", line 93, in run
    _build_ext.run(self)
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
    self.build_extensions()
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "Z:\software\python11\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "R:\allc\eaew\ncnn\setup.py", line 167, in build_extension
    subprocess.check_call(
  File "Z:\software\python11\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'R:\\allc\\eaew\\ncnn', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=R:\\allc\\eaew\\ncnn\\build\\lib.win-amd64-cpython-311\\ncnn\\', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=R:\\allc\\eaew\\ncnn\\build\\lib.win-amd64-cpython-311\\ncnn\\', '-DPYTHON_EXECUTABLE=Z:\\software\\python11\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-DNCNN_PYTHON=ON', '-DNCNN_VULKAN=ON', '-DNCNN_DISABLE_RTTI=OFF', '-DNCNN_DISABLE_EXCEPTION=OFF', '-DNCNN_BUILD_BENCHMARK=OFF', '-DNCNN_BUILD_EXAMPLES=OFF', '-DNCNN_BUILD_TOOLS=OFF', '-A', 'x64', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=R:\\allc\\eaew\\ncnn\\build\\lib.win-amd64-cpython-311\\ncnn\\']' returned non-zero exit status 1.
```

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/tree/master/python#custom-build--install
